### ISSUE TITLE
Inconsistent use of the label revComp/revcomp

### ISSUE THREAD

**Issue by matthuska** [klamkiew/ViralClust#13]
The process `reverseComp` is labeled with `revcomp`, but the config files (conda and local) use the label `revComp` (notice the upper case C). This leads to the process not using the python3 conda environment as intended.

**Comment by klamkiew** [comment]
True, that's rather embarrassing. Apparently, my "default" (global) python3 jumped in and was used for the process, which was perfectly fine on my system due to compatible versions. 
I fixed the typo in the latest commit. Thanks for pointing this out.

**Comment by klamkiew** [comment]
Since there hasn't been any new complaints, I am considering this as closed :) Feel free to poke me, if something else is screwed up.
